create table CUSTOMER (
	customer_id INT,
	customer_name VARCHAR(50),
	customer_email VARCHAR(50),
	customer_address VARCHAR(50)
);
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (1, 'Fletcher Mercer', 'fmercer0@mediafire.com', '06723 Red Cloud Way');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (2, 'Dredi Bercevelo', 'dbercevelo1@stumbleupon.com', '8143 Declaration Hill');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (3, 'Sylvia Gavey', 'sgavey2@bloglines.com', '8454 Doe Crossing Circle');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (4, 'Vern Luttger', 'vluttger3@tripadvisor.com', '1855 Clarendon Circle');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (5, 'Kevan MacParlan', 'kmacparlan4@yellowbook.com', '0973 Fisk Avenue');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (6, 'Herschel Lattey', 'hlattey5@rediff.com', '2240 Fairfield Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (7, 'Reynard Jessup', 'rjessup6@marriott.com', '81078 Summit Court');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (8, 'Merwyn Duffree', 'mduffree7@artisteer.com', '7203 Corscot Junction');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (9, 'Tracie Wanley', 'twanley8@freewebs.com', '573 Nova Street');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (10, 'Derron Leathe', 'dleathe9@mit.edu', '855 Goodland Avenue');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (11, 'Orly Massy', 'omassya@soup.io', '5 Holmberg Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (12, 'Joane Stit', 'jstitb@addthis.com', '963 North Trail');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (13, 'Christean Smale', 'csmalec@mit.edu', '98161 Namekagon Trail');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (14, 'Siouxie MacGilmartin', 'smacgilmartind@alibaba.com', '2281 Superior Pass');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (15, 'Rianon Ainley', 'rainleye@msn.com', '00 Dorton Point');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (16, 'Maressa Sherebrooke', 'msherebrookef@mysql.com', '3 Canary Lane');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (17, 'Cordy Ranshaw', 'cranshawg@mashable.com', '55367 Upham Court');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (18, 'Nettie Chapelle', 'nchapelleh@webs.com', '352 Melody Plaza');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (19, 'Maurise Ivetts', 'mivettsi@vistaprint.com', '2 West Alley');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (20, 'Merwyn O''Mailey', 'momaileyj@printfriendly.com', '93038 Eggendart Drive');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (21, 'Calhoun Lankford', 'clankfordk@nyu.edu', '7 Anthes Alley');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (22, 'Saleem Saiger', 'ssaigerl@google.nl', '00 Arrowood Way');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (23, 'Ad Salliere', 'asallierem@phpbb.com', '35 Bluejay Alley');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (24, 'Major Bleakman', 'mbleakmann@acquirethisname.com', '314 Magdeline Crossing');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (25, 'Collette Bester', 'cbestero@dropbox.com', '87471 Bartelt Plaza');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (26, 'Randene Ranscombe', 'rranscombep@wikispaces.com', '71106 Fairfield Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (27, 'Conway Wyldbore', 'cwyldboreq@yandex.ru', '33999 Green Ridge Plaza');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (28, 'Devora Ortzen', 'dortzenr@geocities.jp', '475 Park Meadow Terrace');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (29, 'Britney Westcarr', 'bwestcarrs@wikispaces.com', '2707 Onsgard Avenue');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (30, 'Harriette Brettle', 'hbrettlet@free.fr', '5973 Comanche Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (31, 'Isidore Huetson', 'ihuetsonu@bbc.co.uk', '058 Vermont Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (32, 'Werner Gockeler', 'wgockelerv@jalbum.net', '5200 Bonner Hill');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (33, 'Elka Mawer', 'emawerw@pagesperso-orange.fr', '65587 Crownhardt Hill');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (34, 'Charmain Rodda', 'croddax@cnet.com', '17 Bowman Pass');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (35, 'Beulah Riddiough', 'briddioughy@istockphoto.com', '2425 Messerschmidt Way');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (36, 'Barn Mager', 'bmagerz@godaddy.com', '66 Rieder Pass');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (37, 'Ninon Maulin', 'nmaulin10@bloomberg.com', '307 Lindbergh Pass');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (38, 'Agneta Macklam', 'amacklam11@phpbb.com', '09546 Hintze Street');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (39, 'Warren Claxton', 'wclaxton12@ustream.tv', '59 Truax Plaza');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (40, 'Randy Eldritt', 'reldritt13@cdc.gov', '6605 Sundown Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (41, 'Creight Parade', 'cparade14@house.gov', '484 Thierer Trail');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (42, 'Joseito Uttridge', 'juttridge15@gizmodo.com', '9317 Mockingbird Junction');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (43, 'Hillary Clementet', 'hclementet16@lulu.com', '60670 Kensington Junction');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (44, 'Oliy Brito', 'obrito17@washingtonpost.com', '59 Kingsford Street');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (45, 'Vinnie Dumberell', 'vdumberell18@sakura.ne.jp', '30639 Summer Ridge Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (46, 'Bond Dunsleve', 'bdunsleve19@springer.com', '3122 Merchant Parkway');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (47, 'Rica Boobyer', 'rboobyer1a@paypal.com', '17 Morrow Park');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (48, 'Kacie Shilito', 'kshilito1b@japanpost.jp', '97 Steensland Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (49, 'Chico Garrity', 'cgarrity1c@ycombinator.com', '6 Briar Crest Lane');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (50, 'Ilsa McCutcheon', 'imccutcheon1d@tamu.edu', '088 Redwing Lane');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (51, 'Erie Soigne', 'esoigne1e@mashable.com', '55 La Follette Drive');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (52, 'Marijo Cordeiro', 'mcordeiro1f@businesswire.com', '737 Center Trail');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (53, 'Archibold Filler', 'afiller1g@tamu.edu', '8 Messerschmidt Junction');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (54, 'Berk Wathall', 'bwathall1h@europa.eu', '09 Kim Hill');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (55, 'Moishe Danels', 'mdanels1i@mlb.com', '634 Banding Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (56, 'Tessie Haffner', 'thaffner1j@ca.gov', '9948 Kings Junction');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (57, 'Luci Neillans', 'lneillans1k@clickbank.net', '97 Maryland Parkway');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (58, 'Stephenie Nimmo', 'snimmo1l@miitbeian.gov.cn', '5 American Crossing');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (59, 'Alley Booth', 'abooth1m@marriott.com', '48192 Crownhardt Avenue');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (60, 'Nelia Baline', 'nbaline1n@auda.org.au', '8 Dorton Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (61, 'Petronia Tanswill', 'ptanswill1o@columbia.edu', '075 Hayes Road');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (62, 'Michaella Petrazzi', 'mpetrazzi1p@mit.edu', '4241 Toban Junction');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (63, 'Grace Blazeby', 'gblazeby1q@ocn.ne.jp', '48166 Kropf Terrace');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (64, 'Sula Murfin', 'smurfin1r@opensource.org', '578 Waxwing Drive');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (65, 'Maegan Barnshaw', 'mbarnshaw1s@state.tx.us', '879 Superior Way');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (66, 'Lindsy Crockley', 'lcrockley1t@msu.edu', '171 Porter Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (67, 'Rahel Rosenbaum', 'rrosenbaum1u@ocn.ne.jp', '16 Emmet Court');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (68, 'Maxy Benoy', 'mbenoy1v@dot.gov', '95 Corry Park');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (69, 'Melesa Hambrook', 'mhambrook1w@illinois.edu', '8491 Coleman Center');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (70, 'Berty Beeswing', 'bbeeswing1x@gizmodo.com', '8 Oxford Parkway');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (71, 'Moria Dymoke', 'mdymoke1y@topsy.com', '3 Nancy Crossing');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (72, 'Nataline Wickes', 'nwickes1z@devhub.com', '117 Tennyson Way');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (73, 'Cristal Greenrde', 'cgreenrde20@cdc.gov', '0069 Charing Cross Avenue');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (74, 'Ros Grazier', 'rgrazier21@uol.com.br', '6520 Debra Hill');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (75, 'Brier Erington', 'berington22@constantcontact.com', '8909 Alpine Lane');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (76, 'Derick Denington', 'ddenington23@cbslocal.com', '531 Toban Drive');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (77, 'Jayme Seeking', 'jseeking24@privacy.gov.au', '22 Warbler Pass');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (78, 'Harrie Mozzetti', 'hmozzetti25@cisco.com', '32 Vernon Alley');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (79, 'Evangeline Pady', 'epady26@examiner.com', '06 Mendota Pass');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (80, 'Lennard Thurby', 'lthurby27@naver.com', '84 Hudson Crossing');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (81, 'Demetris Izatson', 'dizatson28@ihg.com', '1766 Anhalt Court');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (82, 'Harwilll Becker', 'hbecker29@stanford.edu', '9407 Moose Parkway');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (83, 'Margaret Pottinger', 'mpottinger2a@bloomberg.com', '469 Granby Street');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (84, 'Rivalee Corbould', 'rcorbould2b@canalblog.com', '377 Drewry Court');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (85, 'Koralle Frean', 'kfrean2c@w3.org', '78 Annamark Plaza');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (86, 'Gun Ellaway', 'gellaway2d@npr.org', '9241 Corry Crossing');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (87, 'Emlen Covell', 'ecovell2e@npr.org', '92 Forest Dale Park');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (88, 'Crista Cullon', 'ccullon2f@hp.com', '391 Colorado Parkway');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (89, 'Jacquelynn Azema', 'jazema2g@i2i.jp', '16 Declaration Lane');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (90, 'Merrili Mara', 'mmara2h@taobao.com', '59 Truax Trail');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (91, 'Fulvia Khomishin', 'fkhomishin2i@tumblr.com', '4 Coleman Court');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (92, 'Ferdie Gutridge', 'fgutridge2j@hubpages.com', '8676 Ludington Terrace');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (93, 'Talya Toffolo', 'ttoffolo2k@google.it', '5439 Butterfield Way');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (94, 'Suzanne Cormode', 'scormode2l@ft.com', '5604 Ryan Point');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (95, 'Averyl Sowter', 'asowter2m@imgur.com', '70178 Summer Ridge Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (96, 'Chariot Roizin', 'croizin2n@livejournal.com', '27 Birchwood Drive');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (97, 'Laney Rickersey', 'lrickersey2o@51.la', '41403 Chinook Terrace');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (98, 'Raffarty Itchingham', 'ritchingham2p@usatoday.com', '8 Harbort Park');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (99, 'Goldia Staten', 'gstaten2q@google.ru', '664 Crescent Oaks Place');
insert into CUSTOMER (customer_id, customer_name, customer_email, customer_address) values (100, 'Arin Berens', 'aberens2r@twitpic.com', '99694 Kropf Way');
