create table INVOICE_DETAIL (
	invoice_id INT,
	item_name VARCHAR(50),
	item_size VARCHAR(50),
	item_quantity INT
);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (1, 'X-ray', 'S', 18);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (2, 'Delta', '2XL', 14);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (3, 'Oscar', '2XL', 25);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (4, 'Yankee Lima', '2XL', 7);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (5, 'Tango Whiskey', 'M', 5);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (6, 'Quebec Alfa', 'L', 29);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (7, 'Charlie Sierra', 'M', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (8, 'India Sierra', 'S', 9);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (9, 'Kilo Golf', 'M', 25);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (10, 'Foxtrot Uniform', 'L', 12);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (11, 'Hotel', '3XL', 12);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (12, 'Sierra', 'M', 18);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (13, 'Oscar', 'XS', 28);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (14, 'Delta', 'XL', 4);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (15, 'Lima', 'XS', 9);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (16, 'Echo', 'L', 4);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (17, 'Lima', '2XL', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (18, 'Echo Lima', '3XL', 16);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (19, 'Bravo', 'S', 21);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (20, 'Oscar Echo', '2XL', 8);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (21, 'Uniform', '2XL', 15);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (22, 'Hotel', 'M', 11);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (23, 'Papa November', 'S', 13);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (24, 'Romeo', 'M', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (25, 'Echo Delta', '2XL', 11);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (26, 'Kilo Yankee', 'M', 1);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (27, 'Juliett', '3XL', 12);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (28, 'Lima', 'XL', 10);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (29, 'Alfa', 'L', 16);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (30, 'Delta Oscar', 'XS', 13);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (31, 'Charlie November', 'XS', 10);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (32, 'Yankee', 'S', 9);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (33, 'Charlie', 'XL', 5);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (34, 'Romeo Quebec', 'L', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (35, 'Echo', 'S', 21);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (36, 'Golf Lima', 'XL', 4);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (37, 'Yankee Hotel', 'S', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (38, 'Lima', '2XL', 5);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (39, 'Oscar Juliett', 'L', 10);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (40, 'Whiskey Kilo', 'XS', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (41, 'Echo India', 'S', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (42, 'Delta India', 'L', 23);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (43, 'Yankee', 'XL', 1);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (44, 'X-ray Bravo', 'S', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (45, 'Charlie Bravo', 'M', 3);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (46, 'Echo Kilo', 'S', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (47, 'Uniform', 'XS', 3);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (48, 'Echo Tango', '3XL', 1);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (49, 'Bravo Juliett', '2XL', 9);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (50, 'Victor', 'M', 17);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (51, 'Whiskey', '3XL', 15);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (52, 'Romeo', 'S', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (53, 'Kilo', '3XL', 6);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (54, 'Foxtrot Sierra', 'XS', 25);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (55, 'Golf Zulu', 'XS', 1);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (56, 'Victor', 'L', 14);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (57, 'Echo November', 'L', 19);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (58, 'Echo Papa', '2XL', 30);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (59, 'Hotel Lima', 'M', 26);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (60, 'Charlie Alfa', '2XL', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (61, 'Echo Bravo', '3XL', 12);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (62, 'Echo Hotel', 'M', 4);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (63, 'X-ray', 'S', 23);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (64, 'Charlie', 'M', 30);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (65, 'Echo', 'XL', 9);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (66, 'Papa November', 'L', 1);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (67, 'Foxtrot', '2XL', 1);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (68, 'X-ray', 'L', 16);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (69, 'November Foxtrot', 'XL', 6);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (70, 'Quebec', 'M', 28);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (71, 'November Golf', 'S', 15);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (72, 'Delta X-ray', 'M', 23);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (73, 'Foxtrot', 'M', 15);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (74, 'X-ray', 'L', 24);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (75, 'Echo Victor', 'L', 9);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (76, 'Delta', '2XL', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (77, 'Romeo Mike', 'S', 11);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (78, 'Mike', 'XL', 7);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (79, 'India', 'M', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (80, 'Victor', 'S', 13);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (81, 'Mike November', 'M', 3);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (82, 'Romeo India', 'M', 21);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (83, 'India', '2XL', 17);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (84, 'Sierra', 'L', 22);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (85, 'India Yankee', 'XS', 19);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (86, 'Alfa Oscar', 'L', 21);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (87, 'Papa Delta', 'S', 5);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (88, 'Echo', 'S', 21);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (89, 'Whiskey Romeo', 'M', 24);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (90, 'Romeo', 'M', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (91, 'November', 'XS', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (92, 'Yankee Oscar', '2XL', 15);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (93, 'Sierra', '3XL', 2);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (94, 'Oscar Golf', '3XL', 20);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (95, 'Yankee', 'M', 26);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (96, 'Whiskey', '2XL', 22);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (97, 'Tango Delta', 'L', 14);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (98, 'November', 'XS', 23);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (99, 'Lima', '3XL', 16);
insert into INVOICE_DETAIL (invoice_id, item_name, item_size, item_quantity) values (100, 'Juliett Bravo', 'XS', 17);
